name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'https://aplikasi-pertanian.netlify.app/'
          cmd_options: '-a'  
          rules_file_name: '.zap/rules.tsv' 
          fail_action: false  
